### ISSUE TITLE
Data Page Additional Routing Fixes 

### ISSUE THREAD

**Issue by seankim658** [clinical-biomarkers/biomarker-datasetviewer#3]
It seems there are a few more places where the routing needs to be fixed. 

For example, if I'm on the data page at https://hivelab.tst.biochemistry.gwu.edu/biomarker-partnership/data:

![image](https://github.com/biomarker-ontology/biomarker-datasetviewer/assets/33474168/a8fd6fa4-7a99-4d89-a9bb-58eb3296d76f)

And I click on "... view details" for the first row (BCO ID of ARGOS_000009), it routes to https://hivelab.tst.biochemistry.gwu.edu/ARGOS_000009, instead of the correct page at https://hivelab.tst.biochemistry.gwu.edu/biomarker-partnership/data/ARGOS_000009: 

![image](https://github.com/biomarker-ontology/biomarker-datasetviewer/assets/33474168/e8f7c238-a00f-4a98-9ae7-f17e9403f4fa)

If I manually visit the correct url at https://hivelab.tst.biochemistry.gwu.edu/biomarker-partnership/data/ARGOS_000009 I get the correct page:

![image](https://github.com/biomarker-ontology/biomarker-datasetviewer/assets/33474168/d0bb731f-cc8b-4b7d-895f-1970178d177e)

This is similar to the App.js routing that was initially fixed. I'll look for where the additional routing prefix of "/biomarker-partnership/data" needs to get placed.

**Comment by rykahsay** [comment]
Edit src/components/columns.jsx  and try to modify the value shown below :

from 
"/" + params.value.bcoid 
to 
"/biomarker-partnership/data/" + params.value.bcoid


<img width="1174" alt="image" src="https://github.com/biomarker-ontology/biomarker-datasetviewer/assets/20584876/0680fb40-96c3-4d4b-8eca-159c50b0a006">

**Comment by seankim658** [comment]
This has been fixed.
